# Generated by Django 4.1.7 on 2023-03-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_upload_date_upload'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='date_registr',
            field=models.DateField(auto_now_add=True),
        ),
    ]
