# Generated by Django 4.1.7 on 2023-03-10 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_upload_date_registr'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='county',
            field=models.CharField(max_length=40),
        ),
    ]
