# Generated by Django 4.1.7 on 2023-03-10 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_upload_county'),
    ]

    operations = [
        migrations.AlterField(
            model_name='upload',
            name='date_registr',
            field=models.DateField(),
        ),
    ]
