# Generated by Django 4.1.7 on 2023-03-10 18:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_upload_date_registr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='upload',
            old_name='county',
            new_name='country',
        ),
    ]
